### PR TITLE
Show how to check a tarball

### PR DESCRIPTION
**Pull request by krlmlr**
This is just a breadcrumb, and doesn't extend to Singularity or the other options. Also, there's now rchk in rhub -- just not yet in the README: https://github.com/r-hub/rhub/pull/647. I need to run locally because the process is killed on GitHub Actions.

### CODE REVIEW

**Comment by krlmlr** [comment]
This is inconsistent with the "detailed docs" linked just below, let me know if you want me to adapt this or keep the README as is.

**Comment by kalibera** [comment]
Ok, I've added an example for checking the tarball already to the main README. I've removed references to Singularity in the README, SINGULARITY.md remains for historic reference, only, so don't worry about that part.

I am not sure about the --rm flag, isn't the container deleted automatically anyway when the program finishes?

**Comment by krlmlr** [comment]
No, the container finishes but continues to use disk space unless `--rm` is used.

**Comment by krlmlr** [comment]
Thanks for editing the docs!

**Comment by kalibera** [comment]
> No, the container finishes but continues to use disk space unless `--rm` is used.

Ah, thanks, I got it now and updated the documentation to use "--rm" with docker run. In case anyone else is reading this, one can use `docker system df` and `docker ps -a` to see that without "--rm", the containers are stopped but left behind, so that they can be re-started and re-entered, but there is normally no point to do it in these cases.

**Pull request closed without merging**
